apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storageclass-2
  resources:
    requests:
      storage: 1Gi