apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: "mysql-service"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb
          ports:
            - containerPort: 3306
              name: mysql-port
          env:
            # Using Secrets
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name:  mysql-persistent-storage
              mountPath: /var/lib/mysql/
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/role: worker
        kubernetes.io/hostname: "hlasta-pi-140"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-2-pvc
