apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-2-pvc
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storageclass-2
  resources:
    requests:
      storage: 1Gi