apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: databases
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: ebspace/armhf-phpmyadmin:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 250M
            limits:
              cpu: 500m
              memory: 250M
          env:
            - name: PMA_HOSTS
              value: "10.42.3.25;10.42.2.133"
            - name: PMA_PORTS
              value: "3306;3306"
            - name: PMA_USER
              value: "root"
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
